### ISSUE TITLE
SDK should be a separate npm package

### ISSUE THREAD

**Issue by EzraWeller** [SetMatchGames/squad#16]

**Comment by jessebmiller** [comment]
Go through and update all `package.json` files to install that package.

**Comment by EzraWeller** [comment]
- ui
     - react best practice for testing and packaging

 - SDK
    - metastore API, curation API, combined functions in one package
    - one set of tests

**Comment by jessebmiller** [comment]
The SDK is in it's own module and is installed as a file package already so this is basically good to go.

Did a little digging and experimentation on installing from github too.

It's either not obvious or not possible to install from github when the module is in a folder and not the whole repo.

There are two options here and we don't have to decide what to do until there are games that want to install the SDK

Options
1. Keep the modules in this repo and publish the SDK package to npm as part of a build process
  This lets us keep it where it's convinient to work on both the app spec and SDK in the same repo
2. move the SDK package to it's own repo
  This lets people install from github, but we'll probably also want to publish to npm either way
