### ISSUE TITLE
Research and make issues for react best practices we'd like to adopt

### ISSUE THREAD

**Issue by jessebmiller** [SetMatchGames/squad#30]
snake case? camel case? dashes?

**Comment by EzraWeller** [comment]
Read through a few guides and articles today, and I think in terms of the overall structure of our actions and reducers, we're doing okay. There's lots of advice out there on this, but I think what we've got is fairly clear and about as good as what's out there, at least for the stage we're at.

I think we should strongly consider moving to Typescript for the Squad store (what we're currently calling UI). Strong typing will help with managing props and fits well with the validation and typing we're dealing with in both Holochain and Ethereum.

**Comment by EzraWeller** [comment]
For specific patterns we should keep in mind, I like the "smart" and "dumb" component patterns and notes about routing (which we haven't dealt with yet) [here](https://medium.com/lexical-labs-engineering/redux-best-practices-64d59775802e).
