### ISSUE TITLE
Move metastore and curation apis to the folders that back them

### ISSUE THREAD

**Issue by jessebmiller** [SetMatchGames/squad#42]
there is a metastore folder, and a curation folder. the apis for these should be closer to the code they make available to clients.

They will go back to being packages that SDK installs from the filesystem

**Comment by jessebmiller** [comment]
What do you think @EzraWeller does this make sense? Should we do this?

**Comment by jessebmiller** [comment]
Working on consolidating the tests I'm thinking more and more that it makes sense. I'm going to do it as part of that branch.

it'll let us test the metastore and curation APIs much easier.

**Comment by EzraWeller** [comment]
Def agree the code should go together somewhere. What would doing it this way mean for a game dev requiring the SDK in their project?

**Comment by jessebmiller** [comment]
This doesn't change what a game dev needs to install, and with the new structure it'll be something like depending on `@squad/sdk` or something like that. still learning `lerna` and it'll depend on what it publishes to npm. 

This is all presuming it's a game dev requiring the js sdk
