### ISSUE TITLE
Deployable persistent mock metastore

### ISSUE THREAD

**Issue by EzraWeller** [SetMatchGames/squad#79]
- Small npm application that mocks what holochain will do
 - Can be deployed publicly during alpha release to provide a public metastore
 - Can be deployed locally for development (or for any reason)

**Comment by jessebmiller** [comment]
Add a newDeffinitions.toml file

**Comment by jessebmiller** [comment]
I completely rewrote the file structure so that there is a file per definition, and a file per catalog link to avoid concurrency issues and to make everything idempotent.

PR #86

**Comment by jessebmiller** [comment]
#94 Makes squad chess deployable
