### ISSUE TITLE
Mock metastore server can use a simple tracker for peer discovery

### ISSUE THREAD

**Issue by EzraWeller** [SetMatchGames/squad#95]
Since the mock metastore will run on a server in production, we can use this server for peer discovery as well. Peers register their presence on the server and find others registered, probably using the address of the game + address of the format as a channel name for matchmaking, for now.

The idea comes from ["trackers"](https://en.wikipedia.org/wiki/BitTorrent_tracker), which to my understanding were the primary peer discovery tools for p2p software before DHTs became popular.

Once peers have discovered each other, they can use webRTC to play together.

**Comment by jessebmiller** [comment]
Did a little digging, and it looks like we could use https://peerjs.com/

It's got a free public "PeerServer" so we wouldn't have to add it to the mock metastore
