### ISSUE TITLE
Create a work flow to help update documentation along with code (using CI?)

### ISSUE THREAD

**Issue by EzraWeller** [SetMatchGames/squad#96]
Could we use CI to make sure we update documentation as we update code?

For example, could we add a test to CI that says, "if this PR changes the make commands for setting up a dev environment, it must also change the documentation about the dev environment"?

**Comment by jessebmiller** [comment]
Oof probably not?

**Comment by jessebmiller** [comment]
So there are automatic documentation generation tools, but they would not be able to understand when the usage changes vs when it's just code cleanup for example.

Probably worth using automatic documentation generation though that pulls out special documentation comments. I think jsdoc is one and rust has one built in I think

**Comment by EzraWeller** [comment]
Probably not worth messing too much with this right now, I suppose
